### PR TITLE
Create it.json

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by ACTom** [comment]
The translation is incomplete at the moment. Can you complete it?

**Comment by ACTom** [comment]
There are three fields that are not translated.
`    "Save": "",
    "The file has not been saved. Is it saved?": "",
    "Unsaved file": ""
`

**Comment by albanobattistella** [comment]
hi,

I translated all..

https://github.com/albanobattistella/files_mindmap/tree/master/l10n
[https://avatars2.githubusercontent.com/u/34811668?s=400&v=4]<https://github.com/albanobattistella/files_mindmap/tree/master/l10n>
albanobattistella/files_mindmap<https://github.com/albanobattistella/files_mindmap/tree/master/l10n>
This application enables Nextcloud users to open, save and edit mind map files in the web browser. - albanobattistella/files_mindmap
github.com

________________________________
Da: ACTom <notifications@github.com>
Inviato: sabato 1 febbraio 2020 13:22
A: ACTom/files_mindmap <files_mindmap@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [ACTom/files_mindmap] Create it.json (#54)


There are three fields that are not translated.
"Save": "", "The file has not been saved. Is it saved?": "", "Unsaved file": ""

**Comment by ACTom** [comment]
Yes, all your previous fork versions have been translated, but the current version has three new fields.
see [https://github.com/ACTom/files_mindmap/blob/master/l10n/zh_CN.json](https://github.com/ACTom/files_mindmap/blob/master/l10n/zh_CN.json)

**Comment by ACTom** [comment]
You can add these three fields directly to the two files you edit.

**Comment by ACTom** [comment]
You are missing a comma after it.json line 22 and it.js line 23.

**Comment by ACTom** [comment]
Waiting for you to update it.js

**Comment by ACTom** [comment]
Merged, thank you for your contribution.

**Comment by albanobattistella** [comment]
thanks to you!  🙂

________________________________
Da: ACTom <notifications@github.com>
Inviato: sabato 1 febbraio 2020 14:18
A: ACTom/files_mindmap <files_mindmap@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [ACTom/files_mindmap] Create it.json (#54)


Merged, thank you for your contribution.

**Pull request merged**
